
# IMPORT MODULES

In [48]:
import pandas as pd
import numpy as np

# LOAD DATASET - simple variale

In [49]:
df = pd.read_csv("./test.csv")
df.head()

x          y
0  77  79.775152
1  21  23.177279
2  22  25.609262
3  20  17.857388
4  36  41.849864

In [51]:
X = df["x"].values.reshape(-1,1)
y = df["y"].values

# BUILD MODEL

In [103]:
import linear_model
import imp
imp.reload(linear_model)

<module 'linear_model' from 'C:\\Users\\cross\\ml_scratch\\Ch7_Linear_regression\\lab_normal_equation\\windows\\linear_model.py'>

In [104]:
lr = linear_model.LinearRegression(fit_intercept=True)

In [105]:
lr.fit(X, y)

In [106]:
lr.intercept

array([-0.46181077])

In [107]:
lr.coef

array([1.01433536])

In [108]:
lr.coef

array([1.01433536])

In [9]:
lr.predict(X)[:10]

array([ 77.64201157,  20.83923168,  21.85356704,  19.82489633,
        36.05426201,  14.75321955,  62.42698124,  95.90004796,
        19.82489633,   4.609866  ])

In [109]:
lr.predict(X)[:10]

array([77.64201157, 20.83923168, 21.85356704, 19.82489633, 36.05426201,
       14.75321955, 62.42698124, 95.90004796, 19.82489633,  4.609866  ])

# VALIDATION

In [110]:
from sklearn import linear_model
sk_lr = linear_model.LinearRegression(normalize=False)
sk_lr.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [111]:
sk_lr.intercept_ 

-0.4618107736611776

In [112]:
import numpy.testing as npt
npt.assert_almost_equal(sk_lr.intercept_, lr.intercept)

In [113]:
sk_lr.coef_

array([1.01433536])

In [114]:
sk_lr.coef_ 

array([1.01433536])

In [115]:
np.isclose(lr.coef, sk_lr.coef_)

array([ True])

In [116]:
lr.predict(X)[:10]

array([77.64201157, 20.83923168, 21.85356704, 19.82489633, 36.05426201,
       14.75321955, 62.42698124, 95.90004796, 19.82489633,  4.609866  ])

In [117]:
df_test = pd.read_csv("./train.csv")
df_test.head()

x          y
0  24  21.549452
1  50  47.464463
2  15  17.218656
3  38  36.586398
4  87  87.288984

In [118]:
X_test = df["x"].values.reshape(-1,1)

In [119]:
lr.predict(X_test)[:5]

array([77.64201157, 20.83923168, 21.85356704, 19.82489633, 36.05426201])

In [354]:
sk_lr.predict(X_test)[:5]

array([ 23.88223775,  50.25495698,  14.75321955,  38.08293272,  87.78536512])

# LOAD DATASET - multiple variables

In [120]:
df = pd.read_csv("./mlr09.csv")
df.head()

height_in_feet  weight_in_pounds  successful_field_goals  \
0             6.8               225                   0.442   
1             6.3               180                   0.435   
2             6.4               190                   0.456   
3             6.2               180                   0.416   
4             6.9               205                   0.449   

   percent_of_successful_free_throws  average_points_scored  
0                              0.672                    9.2  
1                              0.797                   11.7  
2                              0.761                   15.8  
3                              0.651                    8.6  
4                              0.900                   23.2

In [121]:
y = df["average_points_scored"].values

In [122]:
df.iloc[:,:-1].head()

height_in_feet  weight_in_pounds  successful_field_goals  \
0             6.8               225                   0.442   
1             6.3               180                   0.435   
2             6.4               190                   0.456   
3             6.2               180                   0.416   
4             6.9               205                   0.449   

   percent_of_successful_free_throws  
0                              0.672  
1                              0.797  
2                              0.761  
3                              0.651  
4                              0.900

In [123]:
X = df.iloc[:,:-1].values

In [124]:
X[:5]

array([[  6.8  , 225.   ,   0.442,   0.672],
       [  6.3  , 180.   ,   0.435,   0.797],
       [  6.4  , 190.   ,   0.456,   0.761],
       [  6.2  , 180.   ,   0.416,   0.651],
       [  6.9  , 205.   ,   0.449,   0.9  ]])

# RESCALED

In [125]:
mu_X = np.mean(X, axis=0)
std_X = np.std(X, axis=0)

rescaled_X = (X - mu_X) / std_X

In [126]:
rescaled_X[:5]

array([[ 0.46843663,  0.50336336, -0.12692668, -0.70404955],
       [-0.63137111, -0.99746237, -0.25187012,  0.55584824],
       [-0.41140956, -0.66394554,  0.12296022,  0.19299768],
       [-0.85133266, -0.99746237, -0.59100234, -0.91571238],
       [ 0.68839818, -0.1636703 , -0.00198323,  1.59400403]])

# VALIDATION

In [127]:
lr.fit(rescaled_X, y)

In [128]:
lr.coef

array([-1.67779283,  0.28359762,  2.68586629,  1.12816882])

In [129]:
lr.intercept

array([11.79074074])

In [130]:
sk_lr.fit(rescaled_X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [131]:
sk_lr.coef_

array([-1.67779283,  0.28359762,  2.68586629,  1.12816882])

In [132]:
sk_lr.intercept_

11.790740740740736