# Operation b/t arrays

In [2]:
import numpy as np

In [5]:
test_a = np.array([[1,2,3],[4,5,6]], float)
test_a + test_a, test_a - test_a, test_a * test_a

(array([[ 2.,  4.,  6.],
        [ 8., 10., 12.]]),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[ 1.,  4.,  9.],
        [16., 25., 36.]]))

# Dot product

In [10]:
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)
# test_a * test_b : error
test_a.dot(test_b.T.T)

array([[ 58,  64],
       [139, 154]])

# Broadcating

In [15]:
test_matrix = np.array([[1,2,3],[4,5,6]], float)
scalar = 3
test_matrix + scalar, test_matrix * scalar

(array([[4., 5., 6.],
        [7., 8., 9.]]),
 array([[ 3.,  6.,  9.],
        [12., 15., 18.]]))

##### scalar 외에도 vector - matrix 간 연산지원

In [25]:
a = np.array([[0,10,20,30]])
b = np.array([[0,1,2]])

a.T * b

array([[ 0,  0,  0],
       [ 0, 10, 20],
       [ 0, 20, 40],
       [ 0, 30, 60]])