In [1]:
import numpy as np

In [2]:
def n_size_ndarray_creation(n, dtype=np.int):
    X = np.arange(0, n**2).reshape(n,n)
    return X
    

In [3]:
n_size_ndarray_creation(4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [213]:
def zero_or_one_or_empty_ndarray(shape, type=0, dtype=np.int):
    X = None
    
    if type == 0:
        X = np.zeros(shape = shape, dtype = dtype)
        
    elif type == 1:
        X = np.ones(shape = shape, dtype = dtype)
        
    else:
        X = np.empty(shape = shape, dtype = dtype)
    
    return X

In [217]:
zero_or_one_or_empty_ndarray(shape=(2,2), type=99)

array([[0, 0],
       [0, 0]])

In [240]:
zero_or_one_or_empty_ndarray(shape=(3,3), type=99)

array([[ 1702065442,  1835101810,   573317733],
       [ 1936942451,   577662825,   859054650],
       [ -753030857, -2147480267,   842283321]])

In [193]:
def change_shape_of_ndarray(X, n_row):
    res = None
    if n_row == 1:
        res = X.reshape(-1)
    else:
        res = X.reshape(n_row, -1)
    return res

In [196]:
X = np.ones((32,32), dtype=np.int)
change_shape_of_ndarray(X, 512)

array([[1, 1],
       [1, 1],
       [1, 1],
       ...,
       [1, 1],
       [1, 1],
       [1, 1]])

In [9]:
def concat_ndarray(X_1, X_2, axis):
    if X_1.ndim == 1:
        X_1 = X_1.reshape(1, -1)
    if X_2.ndim == 1:
        X_2 = X_2.reshape(1, -1)
    try:
        X = np.concatenate((X_1, X_2), axis = axis)
    except:
        return False
    return X

In [10]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
c = np.array([1, 2])
d = np.array([5, 6, 7])

In [11]:
concat_ndarray(c, d, 0)

False

In [205]:
def normalize_ndarray(X, axis=99, dtype=np.float32):
    res = None
    if axis == 99:
        res = (X - X.mean()) / X.std()
    else:
        if axis:
            X = X.T
            res = ((X - X.mean(axis=0)) / X.std(axis=0)).T

        else:
            res = (X - X.mean(axis=0)) / X.std(axis=0)
            
    return res

In [206]:
X = np.arange(12, dtype=np.float32).reshape(6,2)
# normalize_ndarray(X)
normalize_ndarray(X, 1)

array([[-1.,  1.],
       [-1.,  1.],
       [-1.,  1.],
       [-1.,  1.],
       [-1.,  1.],
       [-1.,  1.]], dtype=float32)

In [72]:
def save_ndarray(X, filename="test.npy"):
    np.savetxt(X, filename)

In [242]:
X = np.arange(32, dtype=np.float32).reshape(4, -1)
filename = "test.npy"
save_ndarray(X, filename)

In [157]:
def boolean_index(X, condition):
    return np.where(eval("X" + condition))

In [159]:
X = np.arange(32, dtype=np.float32)
boolean_index(X, " > 6")

(array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
        24, 25, 26, 27, 28, 29, 30, 31], dtype=int64),)

In [109]:
def find_nearest_value(X, target_value):
    X = X - target_value
    return X[np.abs(X) == np.abs(X).min()] + target_value

In [110]:
X = np.random.uniform(-1, 1, 10)
print(X)
target_value = 0.3
find_nearest_value(X, target_value)


[-0.88195872 -0.50425173 -0.50459336 -0.66498751  0.24489645 -0.09612159
  0.51847149 -0.34359808  0.72102374 -0.90729367]


array([0.24489645])

In [121]:
def get_n_largest_values(X, n):
    return sorted(X, reverse=True)[:n]

In [122]:
X = np.random.uniform(0, 1, 100)
get_n_largest_values(X, 3)

[0.9962702621889878, 0.9905968931403674, 0.9888079840099341]