In [2]:
import numpy as np

## any & all

In [4]:
a = np.arange(10)
np.any(a>5), np.any(a<0)

(True, False)

In [5]:
np.all(a>5), np.all(a>-1)

(False, True)

In [9]:
test_a = np.array([1,3,0], float)
test_b = np.array([5,2,1], float)
test_a > test_b, test_a == test_b

(array([False,  True, False]), array([False, False, False]))

In [10]:
(test_a < test_b).any()

True

# np.where

In [13]:
a = np.array([1,3,0], float)

In [16]:
np.where(a>0, 't', 'f')

array(['t', 't', 'f'], dtype='<U1')

In [18]:
a = np.arange(5,15)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
a > 10

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [20]:
a = np.array([3.3, np.NaN, np.Inf], float)
np.isnan(a), np.isfinite(a)

(array([False,  True, False]), array([ True, False, False]))

# argmax & argmin

In [25]:
a = np.array([1,2,4,5,6,7,86546,10,565,3,0,345])
np.argmax(a), np.argmin(a)

(6, 10)