# arange

In [3]:
import numpy as np

In [4]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [5]:
a = np.arange(0, 5, 0.1).tolist()
print(a)

[0.0, 0.1, 0.2, 0.30000000000000004, 0.4, 0.5, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9, 1.0, 1.1, 1.2000000000000002, 1.3, 1.4000000000000001, 1.5, 1.6, 1.7000000000000002, 1.8, 1.9000000000000001, 2.0, 2.1, 2.2, 2.3000000000000003, 2.4000000000000004, 2.5, 2.6, 2.7, 2.8000000000000003, 2.9000000000000004, 3.0, 3.1, 3.2, 3.3000000000000003, 3.4000000000000004, 3.5, 3.6, 3.7, 3.8000000000000003, 3.9000000000000004, 4.0, 4.1000000000000005, 4.2, 4.3, 4.4, 4.5, 4.6000000000000005, 4.7, 4.800000000000001, 4.9]


In [6]:
np.arange(50).reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

# ones, zeros and empty

In [8]:
np.zeros(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [9]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.empty(shape=(3,5), dtype=np.int8)

array([[110,   0, 100,   0,  97],
       [  0,  51,   0,  92,   0],
       [101,   0, 110,   0, 118]], dtype=int8)

In [15]:
test_matrix = np.arange(30).reshape(5,6)
print(test_matrix)
print(np.ones_like(test_matrix))
print(np.empty_like(test_matrix))
print(np.zeros_like(test_matrix))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


# identity, eye

In [18]:
np.identity(n=3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.eye(N=3, M=5, k=1, dtype=np.int8)

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]], dtype=int8)

# diag 대각 행렬 값 추출

In [22]:
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

# random sampling

In [30]:
print(np.random.uniform(0,10,100).reshape(2,50)) # from, to, amount of num
print(np.random.normal(0,10,10).reshape(2,5)) # mean, sd, amount of num

[[0.79436122 0.61104753 0.83441228 1.19479403 0.09113256 1.20706125
  0.76466973 1.88120376 1.55343801 1.85292567 0.56336173 0.3005619
  1.99922039 1.94932043 0.08786734 1.81581049 1.20593396 0.95289684
  1.694577   1.19109659 1.33599416 0.48168898 0.75852973 0.77173893
  1.18789459 1.45406975 0.24507905 1.558132   1.01956433 0.19493942
  1.24245737 1.21321625 1.77427854 1.26200997 1.88799719 0.68280497
  0.46095928 0.78440014 0.85637405 1.25872061 0.14584026 0.01396406
  0.49919418 0.51775663 0.54157506 1.66110335 1.48642132 1.31721412
  0.59033865 0.75053512]
 [0.05125749 1.79738986 1.82023776 1.21765401 1.61731246 1.09632101
  0.81452991 0.68185134 1.80212483 1.93718221 1.27656664 1.40223388
  1.23980112 1.86403156 1.3033791  0.02003678 0.95522074 0.5094402
  1.45355557 1.11302961 0.78916229 0.71252667 1.98939916 0.20692864
  0.66365507 1.98468855 1.56684101 0.97460779 0.84899168 0.89958642
  1.73664413 0.09642393 0.32368974 1.43514699 1.76612251 1.44069028
  0.21006097 1.44199302 1