In [2]:
import numpy as np

In [9]:
test_array = np.array([1, 4, 5, 8], float)
test_array
print((type(test_array)))
print(type(test_array[1]))
test_array.dtype

<class 'numpy.ndarray'>
<class 'numpy.float64'>


dtype('float64')

In [14]:
matrix = [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
print(np.array(matrix, int))
np.array(matrix, int).shape

[[1 2 5 8]
 [1 2 5 8]
 [1 2 5 8]]


(3, 4)

In [15]:
tensor = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
np.array(tensor, int).shape

(3, 3, 4)

In [19]:
matrix = [[1,2,5,8], [1,2,5,8], [1,2,5,8]]
matrix2 = np.array(matrix, int)
print(matrix, matrix2)
print(type(matrix))
print(type(matrix2))

[[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]] [[1 2 5 8]
 [1 2 5 8]
 [1 2 5 8]]
<class 'list'>
<class 'numpy.ndarray'>
