# sum

In [23]:
import numpy as np
import math

In [4]:
test_array = np.arange(1, 11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
test_array.sum(dtype=np.float)

55.0

# axis (완전 중요)

#### 모든 operation func. 실행할 때, 기준이 되는 dimension

In [14]:
test_array = np.arange(1,28).reshape(3,3,3)
test_array

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [15]:
test_array.sum(axis=2), test_array.sum(axis=1), test_array.sum(axis=0)
# 0 이 제일 처음(바깥) bracket에 해당하는 차원계산
# 제일 높은 axis가 맨 안쪽 list 계산한다고 보면 됨.

(array([[ 6, 15, 24],
        [33, 42, 51],
        [60, 69, 78]]),
 array([[12, 15, 18],
        [39, 42, 45],
        [66, 69, 72]]),
 array([[30, 33, 36],
        [39, 42, 45],
        [48, 51, 54]]))

# mean & std

In [19]:
print(test_array)
test_array.mean(), test_array.mean(axis=0)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


(14.0,
 array([[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]]))

In [20]:
test_array.std(axis=0)

array([[7.34846923, 7.34846923, 7.34846923],
       [7.34846923, 7.34846923, 7.34846923],
       [7.34846923, 7.34846923, 7.34846923]])

In [26]:
np.exp(test_array), np.sqrt(test_array), math.exp(1)

(array([[[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
         [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
         [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]],
 
        [[2.20264658e+04, 5.98741417e+04, 1.62754791e+05],
         [4.42413392e+05, 1.20260428e+06, 3.26901737e+06],
         [8.88611052e+06, 2.41549528e+07, 6.56599691e+07]],
 
        [[1.78482301e+08, 4.85165195e+08, 1.31881573e+09],
         [3.58491285e+09, 9.74480345e+09, 2.64891221e+10],
         [7.20048993e+10, 1.95729609e+11, 5.32048241e+11]]]),
 array([[[1.        , 1.41421356, 1.73205081],
         [2.        , 2.23606798, 2.44948974],
         [2.64575131, 2.82842712, 3.        ]],
 
        [[3.16227766, 3.31662479, 3.46410162],
         [3.60555128, 3.74165739, 3.87298335],
         [4.        , 4.12310563, 4.24264069]],
 
        [[4.35889894, 4.47213595, 4.58257569],
         [4.69041576, 4.79583152, 4.89897949],
         [5.        , 5.09901951, 5.19615242]]]),
 2.718281828459045)

# concatenate

In [33]:
a = np.array([[1,2],[3,4]])
b = np.array([[4,5],[6,7]])
np.vstack((a,b)), np.hstack((a,b))

(array([[1, 2],
        [3, 4],
        [4, 5],
        [6, 7]]),
 array([[1, 2, 4, 5],
        [3, 4, 6, 7]]))

In [34]:
np.concatenate((a,b), axis=0),np.concatenate((a,b), axis=1)

(array([[1, 2],
        [3, 4],
        [4, 5],
        [6, 7]]),
 array([[1, 2, 4, 5],
        [3, 4, 6, 7]]))

In [41]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])